---
- name: Ensure BookHaven Docker network exists
  community.docker.docker_network:
    name: "{{ frontend_network }}"
    state: present

- name: Pull BookHaven frontend image
  community.docker.docker_image:
    name: "{{ frontend_image }}"
    source: pull
    force_source: true

- name: Run BookHaven frontend container
  community.docker.docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    recreate: true
    restart_policy: unless-stopped
    published_ports:
      - "{{ frontend_port }}:80"
    networks:
      - name: "{{ frontend_network }}"
