---
- name: Ensure BookHaven Docker network exists
  community.docker.docker_network:
    name: "{{ backend_network }}"
    state: present

- name: Pull BookHaven backend image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull
    force_source: true

- name: Run BookHaven backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    recreate: true
    restart_policy: unless-stopped
    published_ports:
      - "{{ backend_port }}:5000"
    env:
      MONGO_URI: "{{ backend_mongo_uri }}"
      PORT: "5000"
    networks:
      - name: "{{ backend_network }}"
